name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Analytics IDs
        env:
          CLARITY_ID: ${{ secrets.CLARITY_ID }}
          GA_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        run: |
          # Verify secrets are available and properly formatted
          if [ -z "$CLARITY_ID" ]; then
            echo "Error: CLARITY_ID is not set"
            exit 1
          fi
          
          if [ -z "$GA_ID" ]; then
            echo "Error: GA_MEASUREMENT_ID is not set"
            exit 1
          fi
          
          # Verify GA_ID format (should start with G-)
          if [[ ! "$GA_ID" =~ ^G-[A-Za-z0-9]+$ ]]; then
            echo "Error: GA_MEASUREMENT_ID should start with 'G-' followed by alphanumeric characters"
            exit 1
          fi
          
          echo "Analytics IDs validated successfully"

      - name: Replace Analytics IDs
        env:
          CLARITY_ID: ${{ secrets.CLARITY_ID }}
          GA_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        run: |
          # Replace the placeholders
          sed -i "s|__CLARITY_ID__|${CLARITY_ID}|g" config.js
          sed -i "s|__GA_ID__|${GA_ID}|g" config.js
          
          # Verify the replacements
          echo "Verifying replacements..."
          if grep -q "__CLARITY_ID__" config.js; then
            echo "Error: CLARITY_ID was not replaced"
            exit 1
          fi
          if grep -q "__GA_ID__" config.js; then
            echo "Error: GA_ID was not replaced"
            exit 1
          fi
          
          # Print first few characters of IDs for verification (safely)
          echo "CLARITY_ID prefix: ${CLARITY_ID:0:4}..."
          echo "GA_ID prefix: ${GA_ID:0:4}..."
          echo "Replacements verified successfully"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          
      - name: Verify Deployment
        run: |
          echo "Deployment completed. Please verify analytics at:"
          echo "Microsoft Clarity: https://clarity.microsoft.com/"
          echo "Google Analytics: https://analytics.google.com/" 