name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace Analytics IDs
        env:
          CLARITY_ID: ${{ secrets.CLARITY_ID }}
          GA_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        run: |
          # Verify secrets are available
          if [ -z "$CLARITY_ID" ]; then
            echo "Error: CLARITY_ID is not set"
            exit 1
          fi
          if [ -z "$GA_ID" ]; then
            echo "Error: GA_MEASUREMENT_ID is not set"
            exit 1
          fi
          
          # Replace the placeholders
          sed -i "s|__CLARITY_ID__|${CLARITY_ID}|g" config.js
          sed -i "s|__GA_ID__|${GA_ID}|g" config.js
          
          # Verify the replacements
          echo "Verifying replacements..."
          if grep -q "__CLARITY_ID__" config.js; then
            echo "Error: CLARITY_ID was not replaced"
            exit 1
          fi
          if grep -q "__GA_ID__" config.js; then
            echo "Error: GA_ID was not replaced"
            exit 1
          fi
          echo "Replacements verified successfully"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages 